### PR TITLE
Changing ECPublicKeyParameters to ECPoint

### LINKED ISSUE #42: Change signatures in Initiator.cs
The signatures of VerifyProof and RandomiseToken should be modified to take ECPoint K instead of ECPublicKeyParameters K.

### PR DESCRIPTION
**Pull request by martstr**
Closes #42

### CODE REVIEW

**Review by HenrikWM — DISMISSED** [review]
LGTM 👍

**Comment by HenrikWM** [comment]
Can you bump the version in `src\Directory.Build.props` to `2.0.0` before merging this? Or make the change in method-signature opt-in and deprecating the existing? In which case you can bump the minor-version instead to `1.5.0`. Can you update the code @martstr?

We should merge this one after #46, #47, #48 are merged.

**Comment by HenrikWM** [comment]
Small merge-conflict @martstr :) If you can ping Tjerand after you've pushed I can merge this and release version 2.0.0 🎉

**Comment by HenrikWM** [comment]
Small merge-conflict @martstr :) If you can ping Tjerand after you've pushed I can merge this and release version 2.0.0 🎉

**Comment by martstr** [comment]
OK, I think I've done what I was supposed to do now. @tjesi and @HenrikWM, please check.

**Pull request closed without merging**
